version:     "0005d--16-Feb-2022"
copyright:   "2022"
author:      "C. BinKadal"
title:       "SP221: System Programming 2022-1"
githublink:  "https://github.com/cbkadal/sp221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]

